/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SampleImmutableERC1155Soulbound } from "./SampleImmutableERC1155Soulbound";
export type { SampleImmutableERC721Soulbound } from "./SampleImmutableERC721Soulbound";
