/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SampleImmutableERC1155Soulbound__factory } from "./SampleImmutableERC1155Soulbound__factory";
export { SampleImmutableERC721Soulbound__factory } from "./SampleImmutableERC721Soulbound__factory";
